version: "3"
services:
  plugin:
    container_name: plugin
    build:
      context: ./plugin
      dockerfile: Dockerfile
      args:
        WS_BASE_URL: ws://localhost:65520
    ports:
      - "3000:3000"
    networks:
      - ink-network
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "65520:65520"
    networks:
      - ink-network
    volumes:
      - ./storage:/usr/src/app/storage
networks:
  ink-network:
