version: "3"
services:
    plugin:
        container_name: plugin
        build:
            context: ./plugin
            dockerfile: Dockerfile
        ports:
            - "3000:80"
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "65520:65520"
