apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: default
  labels:
    name: digitalocean-dns
type: Opaque
stringData:
    access-token: genereate-new-secret-here-current-revoked

