apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: default
  labels:
    name: digitalocean-dns
type: Opaque
stringData:
    access-token: 57fbc1eecca8d689b01f1faa45d773132f211f63d7aea940c690659265f0ccce

