apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
      istio-egressgateway:
        enabled: false
    security:
      selfSigned: true
    global:
      mtls:
        enabled: true
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
