apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
    global:
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
 