apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUowbDZPaTNXaXhZSUZlbDRkMDh5NFV3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01qUTRNVEUxTVdZdFpXUXhaQzAwTlRnMUxUZ3hZbVV0TkRBd1l6UTBaREJrTXpOaApNQjRYRFRJd01ESXhOakUyTlRJMU1sb1hEVEkxTURJeE5ERTNOVEkxTWxvd0x6RXRNQ3NHQTFVRUF4TWtNalE0Ck1URTFNV1l0WldReFpDMDBOVGcxTFRneFltVXROREF3WXpRMFpEQmtNek5oTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcDR1U2toTWdTMzBmbkI5dU13dldCNE1UMDFML3FBN1ZzcVNlLzVkNQphNTMxbTlsY0hVR2Z1OFY4bmFnM2trQU5tYTk4emIreVFOQmVPUG42bkErWlhYUm5pd0NnUTV5UjhQQ2ZUU2h4CjVOZDd3b0V4WTBmTFBHMnpwbUdKcEhBS0R1VWZHb2l1eTJuSEZPYkxoK05OUVFEdEhMeENtWFp5Z0dTdkREYzIKai9Bb2N3cWpOeGIyWkxHZCtYY2NsZGt4dlUybWtMRXUvTEMvYnlKMVpYbVM5aUNuRldha2N3cGxrdTBzSUNlcAozbTExS0FISlFJUlo4NDQ2cWNxZmhNMDIraGQ2bENwTnBtNGhWd3BncGxYQUk4cjdRZXk0Z2RhUVVDd1krckxHCnN3YnV4UVFmVzdMWVJlUW5BaFV1Z0gxaXdieVJjSSs4N0JVdUxGQmNnVUdrRVFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpYYVZ5eS8yVEtKRzhsbHpac05mam9Oc1kxTi9PbU50cVI2cWhYSi96Wk9ZckI2WTVaOWNjNndkNjVoNGhYSUJNCnJZVXgvYVpXb21nS0xvbXVoNm9XZkdYTW5VSDlta05EY3pqMXZWdUQ4RE93cHdUYm1VNnFVdFBPRWVvamdTaHQKQkVCN3FRRWk2bmVNaFhQSVpYWVp3QnA1V1ZPRGpzMjdXQVIzRm5OUnFwQUg3RjJiVnNDbDZrZnE2eTFvalNHWQpwOFBCeTlQQjVyV3BQaUpOMUZzcDd3SjhFTzVFT3l2b3pPdUhQT29lTUF0dHJkbkpWQUc2bGIwSDlGOE00cThYCnZpM0lwN3paYW1PMTRFdUw0Vml5eUFveFJZVS9KNjJRejROdGhvZXk3bkxnNGVOOExaWHpFZzlqTHIvdTk0dUIKek95SFpQcE9lQ3ExdHQyYmNQcUErdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.65.145.64
  name: gke_ink-server_europe-west6-a_europe
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU5hZVNTTHNuaHRTMkVaWFN5cmJlTzB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1kyRmlOMkkxTldJdE5qTXpaQzAwTURNNUxXSXlOamt0TVdVNU9EUXdOMkZrTkRJNQpNQjRYRFRJd01ESXhOakUyTlRJME5sb1hEVEkxTURJeE5ERTNOVEkwTmxvd0x6RXRNQ3NHQTFVRUF4TWtZMkZpCk4ySTFOV0l0TmpNelpDMDBNRE01TFdJeU5qa3RNV1U1T0RRd04yRmtOREk1TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBekp5cFdueldobXRqaVhkZVBvS3BVVlJabXdIVjkrbGpITkxWaURyWgp5NUFtTm9DSVJ2UWZuY1VKeTAzZXh4TWNBUTQ2SEYvY3I3VzJUUGtaTUhPQkJheW56UjVOdS9udnRqR0trNnFYCnpNQkQydFNMZHovZkRwYktFZk5NNlY2MzR0MjJNemtDMkJjSWk2aWUyeldYZEJDZkMreXQ1VERCVk1OdldtZm0KRGoxSEZaZlRnZVFrdG83U3lyRTFiUUY5L0Y1M1ExTUhQU1JJNXFqa1pueEpZZWFLS25pWEYxUUY0RHJBUlp2TApsbVhQT2VCbHJZVUFvSEdJVlR5SWxKM2pobTVVSWhLNkRZYzFWb0JUaEcyMDB2N2Q2TGdMK0EwcDBYSWVlbVlZClVPYkR3MisrRzUvSWhtdklmNVZzSEVhZXJldHhEZDNNaXNnZkkwdHZpbWxUYndJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQplOUxXdkhrQVR1a2xyOVlMUk9qOVVpenFobm9uaVJZZU1GZmJaQWpUNjVVNXROTWxuUE9kcnZIK0ZmNjVYTVd6CjFxVm5BN0R2UUhoNksrUGpZLy90ZEJ2d2NmYVE5QlZnSWJYbWlKWmxXM2M2RTJRL0JqWGpUanJHMjNMM0Q2MDEKeDBkWFZGMjNRK0oxTGU5Z2ovdkwzNXd1QmlQV2J5ZS9FeWdRTzFkeHY3bkRWNWZUcktTYXRKUm85cGNlQjFyMwp3MjB6clY0aDUxSDVMK3V5dzUwMVZtdlYyQUFDNlVnQVlYem1GLzZYTHBodVl6ZFlXOEFkenFUVFROWTgzc2E5CkJDVVJaREJSaWs4VE1mSlVJL0hxNzFuNERRaEt3Q1k1UEZiZEp4ZDQ3RGRXQXJFWHFxaEFya3laTFZuY0pmQ04KK2YxT1lMczhzWlFXekZwQWhpZ21JZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.245.191.255
  name: gke_ink-server_us-east4-a_usa
contexts:
- context:
    cluster: gke_ink-server_europe-west6-a_europe
    user: gke_ink-server_europe-west6-a_europe
  name: europe
- context:
    cluster: gke_ink-server_us-east4-a_usa
    user: gke_ink-server_us-east4-a_usa
  name: usa
current-context: europe
kind: Config
preferences: {}
users:
- name: gke_ink-server_europe-west6-a_europe
  user:
    auth-provider:
      config:
        access-token: ya29.ImW9B8ui8XvWB1H68SS-2UwY-Oubd1Rmg80JGWXd_OcX2kwc-DKH6gPZEeeOSQFmY1s9adX9ZsqGH1bOBrdbxs305iQIKvC3K0sFykwi_WAFjevWpop4Htbj3VDfqoEW8F68Q03F8w
        cmd-args: config config-helper --format=json
        cmd-path: /home/user/Downloads/google-cloud-sdk-276.0.0-linux-x86_64/google-cloud-sdk/bin/gcloud
        expiry: "2020-02-16T19:06:46Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_ink-server_us-east4-a_usa
  user:
    auth-provider:
      config:
        access-token: ya29.ImW9B8ui8XvWB1H68SS-2UwY-Oubd1Rmg80JGWXd_OcX2kwc-DKH6gPZEeeOSQFmY1s9adX9ZsqGH1bOBrdbxs305iQIKvC3K0sFykwi_WAFjevWpop4Htbj3VDfqoEW8F68Q03F8w
        cmd-args: config config-helper --format=json
        cmd-path: /home/user/Downloads/google-cloud-sdk-276.0.0-linux-x86_64/google-cloud-sdk/bin/gcloud
        expiry: "2020-02-16T19:06:46Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
