apiVersion: install.istio.io/v1alpah2
kind: IstioControlPlane
metadata:
  name: default
spec:
  unvalidatedValues:
    global:
      meshID: inkmesh
  values:
    gateways:
      istio-ingressgateway:
        env:
          ISTIO_MESH_NETWORK: usa
        sds:
          enabled: true
    global:
      controlPlaneSecurityEnabled: true
      k8sIngress:
        enableHttps: true
        enabled: true
        gatewayName: ingressgateway
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: b375a234-53e1-11ea-b710-42010aac0075
            gateways:
            - address: 34.65.123.10
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes
      multiCluster:
        clusterName: a1195f20-53e1-11ea-bbd8-42010a96011e
      network: usa
    pilot:
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: b375a234-53e1-11ea-b710-42010aac0075
            gateways:
            - address: 34.65.123.10
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes

