apiVersion: install.istio.io/v1alpah2
kind: IstioControlPlane
metadata:
  name: default
spec:
  unvalidatedValues:
    global:
      meshID: inkmesh
  values:
    gateways:
      istio-ingressgateway:
        env:
          ISTIO_MESH_NETWORK: usa
        sds:
          enabled: true
    global:
      controlPlaneSecurityEnabled: true
      k8sIngress:
        enableHttps: false
        enabled: true
        gatewayName: ingressgateway
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: cb198b4f-3d28-11ea-9bdf-42010aac0017
            gateways:
            - address: 34.65.123.10
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes
      mtls:
        enabled: true
      multiCluster:
        clusterName: d492b50b-3d28-11ea-91e8-42010a9600cf
      network: usa
    pilot:
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: cb198b4f-3d28-11ea-9bdf-42010aac0017
            gateways:
            - address: 34.65.123.10
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes
    security:
      selfSigned: true

