apiVersion: install.istio.io/v1alpah2
kind: IstioControlPlane
metadata:
  name: default
spec:
  unvalidatedValues:
    global:
      meshID: inkmesh
  values:
    gateways:
      istio-ingressgateway:
        env:
          ISTIO_MESH_NETWORK: europe
        sds:
          enabled: true
    global:
      controlPlaneSecurityEnabled: true
      k8sIngress:
        enableHttps: true
        enabled: true
        gatewayName: ingressgateway
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: Kubernetes
          usa:
            endpoints:
            - fromRegistry: a1195f20-53e1-11ea-bbd8-42010a96011e
      multiCluster:
        clusterName: b375a234-53e1-11ea-b710-42010aac0075
      network: europe
    pilot:
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: Kubernetes
          usa:
            endpoints:
            - fromRegistry: a1195f20-53e1-11ea-bbd8-42010a96011e

