apiVersion: install.istio.io/v1alpah2
kind: IstioControlPlane
metadata:
  name: default
spec:
  unvalidatedValues:
    global:
      meshID: inkmesh
  values:
    gateways:
      istio-ingressgateway:
        env:
          ISTIO_MESH_NETWORK: usa
        sds:
          enabled: true
    global:
      controlPlaneSecurityEnabled: true
      k8sIngress:
        enableHttps: false
        enabled: true
        gatewayName: ingressgateway
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: 7a8b1d83-50e5-11ea-a5ce-42010aac0011
            gateways:
            - address: 34.65.71.3
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes
            gateways:
            - address: 35.245.34.52
              port: 443
      mtls:
        enabled: true
      multiCluster:
        clusterName: 658e3341-50e5-11ea-af86-42010a9600bb
      network: usa
    pilot:
      meshNetworks:
        networks:
          europe:
            endpoints:
            - fromRegistry: 7a8b1d83-50e5-11ea-a5ce-42010aac0011
            gateways:
            - address: 34.65.71.3
              port: 443
          usa:
            endpoints:
            - fromRegistry: Kubernetes
            gateways:
            - address: 35.245.34.52
              port: 443
    security:
      selfSigned: false

