apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: default
  labels:
    name: digitalocean-dns
type: Opaque
stringData:
    access-token: a1af6eec8839d59e18684d37a156b8baad5f3db62f4e533072e060d46717e637
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'edi.sinovcic@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector: {}
      dns01:
        provider: 'digitalocean'
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token 
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'edi.sinovcic@gmail.com'
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
---
# apiVersion: cert-manager.io/v1alpha2
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
#   namespace: istio-system
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: 'edi.sinovcic@gmail.com'
#     privateKeySecretRef:
#       name: ingress-cert
#     http01: {}
# ---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-ink
  namespace: default
spec:
  secretName: ink-remix.blockchain-it.hr-tls-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "ink-remix.blockchain-it.hr"
  dnsNames:
  - 'ink-remix.blockchain-it.hr'
  # acme:
  #   config:
  #   - dns01:
  #       provider: 'digitalocean'
  #       digitalocean:
  #         tokenSecretRef:
  #           name: digitalocean-dns
  #           key: access-token 
  #     domains:
  #     - 'ink-remix.blockchain-it.hr'
    # - http01:
    #     ingressClass: istio
    #   domains:
    #   - ink-remix.blockchain-it.hr
    
    # - http01:
    #     ingress:
    #       class: nginx
    # - http01:
    #     ingressClass: istio
    #   domains:
    #     ink-remix.blockchain-it.hr
