apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU1QbjdNUy8zbWsyUHZ3QVNnckt3THN3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pUY3lNbUppTlRBdE5XTm1NQzAwTUdNM0xUZzNOMk10TW1NNE9EYzFNbVppWWprMQpNQjRYRFRJd01ESXhPVEV4TXpZME4xb1hEVEkxTURJeE56RXlNelkwTjFvd0x6RXRNQ3NHQTFVRUF4TWtaVGN5Ck1tSmlOVEF0TldObU1DMDBNR00zTFRnM04yTXRNbU00T0RjMU1tWmlZamsxTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbjFtdmdKbis3dERWTFAzblhQLytEWEQ2YkE0Mk1RZDNDb3RWclFaVAowSlZYSWhoZVhSeWJuK2p1bWhsbW1WQ241d3QwZXl2NEVlYlVOMnRkaWdKTWVSV2tsK1JOSUE0TE9qTnUvWVBECmtpUERZQ2xxWHBQeDM4cHR6K29sdFlyTWN6eG9udDViUmE3N2ZraHNuNFMxamFIVVhSc3RDZTlwLzg1ZXhqZ0oKYTdac0FjQzNPRUE3b2ZMR0h2NHQvVkRISWg0Z2x3NjJIQ0NMc285Yk5EczE2SU1ocFBWZzdtcUNTeEdLOUlKSwo5aEVsZmVodEQydkxCYXNLMXdteGRIdExKQklsUDZaOWZrODhKNklEci9sMUhBeWcyTVRRbmVDeGoyK3V3Sk1JCmtvZlJXRW55UWZsOFNnNjJBOFcvc1dsenJWRjRVdGxadWxuOXdCd2cvVEFQRXdJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpVRW1tQjRxM3pBNUczUEQ2Wk1pdzd4VHVMUGlyM29OMnh4cy9HOElJT05BTXVkdHV3eTFvR3RqdU5lSTk5akxoCmZQdUMwb3VlZko3SGpJVXZuc3ptN1BCVGRxdzFEUmEvRHhxWk1DSSsvcGdVK2ltemdjTFpQbUQxbGdHKzdkbDcKOXpoRzZLVXNIdmdHSXkvaldaZjcrdFIyUUJjTUV3MkxzSExsWSt3NXh6Yy84SStVUHpzRk04d0VwMzJ5NmlRcwpHWkxMbXY3ZDNjMFJTZjcrVmQvbHcxWS9DUklzWUJ6YUhrNU1jNFpmUWdVVkN6d0VycUl5ZHJaSFhlY0VRVTVZCjMwdFZuNm5vTklMUlBnK1NBUEFNNTVCbGR0U1ZtZ1h1TE9IVVBxL1JMTmF4WmNWcjhRVHkzWUlFejJWcmJsK1oKc2lQSVhBTXhiLzhYYUxsdVloM3k1Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.245.118.225
  name: gke_ink-server_us-east4-a_usa
contexts:
- context:
    cluster: gke_ink-server_us-east4-a_usa
    user: gke_ink-server_us-east4-a_usa
  name: usa
current-context: usa
kind: Config
preferences: {}
users:
- name: gke_ink-server_us-east4-a_usa
  user:
    auth-provider:
      config:
        access-token: ya29.Ima9B906LGb4Tfv9IS_FhNfQy2k4aiGxdiLxCtTtSxd8STZjkSz9bq-uZb2RUQ_TZMkpZNs2qM6lTTvWMwRKypB-R5FHj2ViQ6Kx8co7YMUHesyEIXA0Cjy47N1c7TqtO2ViaU1Od-E
        cmd-args: config config-helper --format=json
        cmd-path: /home/user/Downloads/google-cloud-sdk-276.0.0-linux-x86_64/google-cloud-sdk/bin/gcloud
        expiry: "2020-02-20T13:25:09Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
