apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: ink
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'edi.sinovcic@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: ink
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'edi.sinovcic@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
