apiVersion: v1
kind: Service
metadata:
  name: plugin-svc
  labels:
    app: ink
spec:
  type: ClusterIP
  selector:
    app: ink
  ports:
  - name: plugin-port
    protocol: TCP
    port: 80
    targetPort: 80
