apiVersion: v1
kind: Service
metadata:
  name: plugin-svc
  labels:
    app: ink
    component: plugin-svc
spec:
  type: ClusterIP
  selector:
    app: ink
    component: plugin
  ports:
  - name: http
    port: 80
    targetPort: 3000
