name: 'Push'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v1'
    - name: 'Run build scripts'
      run: 'CIRCLE_BRANCH=${GITHUB_REF##*/} scripts/build.sh'
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'Trigger deployment'
      run: scripts/deploy.sh
  publish-helm:
      runs-on: 'ubuntu-latest'
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"     
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
        with:
          charts_dir: "kubernetes/ink/"
