name: 'Push'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish-helm:
      runs-on: 'ubuntu-latest'
      steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master
          charts-folder: kubernetes/ink/
